sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-feefifofum
before_install:
- pip install --user awscli
script: make
deploy:
  provider: script
  script: make release && aws s3 cp pkg/payload.zip "s3://$BUCKET/$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: bqWO0F+fuHbEU3kr+odBc+QTBOEh+qzRAd/CRQeMAF4YlKZNbFqAlM9FKDV+EYLkWZ/P5nuyojIG9buTnYVINS0fNP+WLOY665zuy6qL8Lpw86aVLyswLmuxC4n4a3wrXDplhL6ODQ0j4CR+u1oTBmHdh6wuR/FhRffE8tjb9Oqrk5uzafLXKbPHYBCNpClhiAWR6D4uVWzYeqOV9/f8ZLSdEq30jvKvAZNCNAFjkVKhv9XJWKycHm42tloNt08H4JRJQ9k0C2evjCLLBd4nVYRdk1hLEStBX65S3e4gQBEG0Et82YVVI9ftXhjp6vCs6jbzO0u9lhgX2Rpdoty5X1v293pE3kklwqXa/gcmRSeKw05SSDFCzCpLOrRXHRnILS6+jT3DI6oZgtUlYvWCCZo26slHyHhW/lUBMFwo9sZgCWUo5b/TD7cYKtog8N9EVp6ZFscMbLMuq+Y3+QBsgoi2lt3/E9JJc9RBNkxj7WDTH2c3F/Sc/PWPelpK+ZqNecebh59YXvqwr5wHNfwJIQB6ObuB19xoGp18B9zk2JsqKnOlRGYl1KM9tNqyuHJKaR6MdL08wgoPfq1F8Y5qFDFbva6jq8bsIq/AlFywpYXU9Mrp/9N2VQgS3SJ04DXVtM+tt81JhiaI6R/3OJZ3f9tQYz2cRHz72AGNqK5Kj5g=
